### ISSUE TITLE
(Optionally) stop deleting join messages

### ISSUE THREAD

**Issue by ForNeVeR** [ImoutoChan/GreenCaptchaBot#3]
I have a chat where I usually review all the new participants (and often disposse of them after a closer examination). So, I don't need the bot to remove the join messages from the chat; quite the contrary, I want these messages to stay in the chat. This is only required for the users who wasn't banned by the bot.

Is it possible to have some per-chat configuration for the bot, and add this as a setting? I can see that currently it has no configuration and is expected to work out-of-the-box, without storing any data (per-chat of whatever).

Would you advise me to fork the bot and deploy my own instance, or is it somehow possible to add this setting to your upstream bot?

**Comment by ImoutoChan** [comment]
It will be hard with persistency. I don't really want to add a dependency on some storage to the bot. 

I have 2 options in mind.

1) We can add a memory only settings, which would reset on every restart (rarely happens anyway). You would need to call some command in each of the chats, where you want deviant settings. For example, '/retainEnterMessage'

2) We can add remote settings, for example a file in this repository. There we can in some format describe settings for the particular chat ids. Then in our bot we would load the settings from the file on startup.

What do you think?

**Comment by ForNeVeR** [comment]
Option 1 looks too fragile to me, I don't like this idea much.
Option 2 would be okay. I don't want a file in the repository with my chat id, but I could add support for a simple settings file, and then override this config in my bot instance.
