### ISSUE TITLE
Bug: bot incorrectly sets restrictions for new chat members

### ISSUE THREAD

**Issue by kreuwont** [ImoutoChan/GreenCaptchaBot#9]
New users joining to the chat can not write messages even after successfully solving the captcha.

**Suspected reason:** for getting actual restrictions for current user you use [getchatmember](https://core.telegram.org/bots/api#getchatmember) from tg bot api. This method return struct with status field which can accept one of several values (restricted, member, owner and other). The reason is that the fields with the current restrictions information for user are given only to users with 'restricted' status (and new users have 'member' status and these fields are not sent in the response => .NET sets defalt values for those model's fields).

[Telegram api answer example](https://prnt.sc/wgek90)

**Comment by ForNeVeR** [comment]
> **Suspected reason:** […] fields are not sent in the response => .NET sets defalt values for those model's fields).

Your hypothesis isn't right: as I can see, the corresponding values [are nullable bools](https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/Types/ChatMember.cs#L44-L50).
